#!/bin/sh
# yum install -y sysstat

#Ensure 3 arg
if [ -z $1 ] || [ -z $2 ] ;then
     echo "Please include 2 arguments, eg."
     echo "Usage: $0 {used warning} {used critical}"
     exit 3
fi

#Ensure warning is greater than critical limit
if [ $1 -gt $2 ];then
  echo "Please ensure warning is less than critical, eg."
  echo "Usage: $0 10 20"
  exit 3
fi

CPU=`/usr/bin/mpstat 1 1|grep all|tail -1`
echo $CPU
CPUIDLE=`echo ${CPU}|awk '{print $12}'|awk -F. '{print $1}'`
CPUUSED=`expr 100 - $CPUIDLE`

CPUUSER=`echo ${CPU}|awk '{print $3}'|awk -F. '{print $1}'`
CPUUSYS=`echo ${CPU}|awk '{print $5}'|awk -F. '{print $1}'`
CPUIO=`echo ${CPU}|awk '{print $6}'|awk -F. '{print $1}'`

if [ $CPUUSED -gt $2 ];then
        echo "CRITICAL: Used=$CPUUSED% | CpuUsed=$CPUUSED CpuUser=$CPUUSER CpuSys=$CPUUSYS CpuIOWait=$CPUIO"
        exit 2
elif [ $CPUUSED -gt $1 ];then
        echo "WARNING: Used=$CPUUSED% | CpuUsed=$CPUUSED CpuUser=$CPUUSER CpuSys=$CPUUSYS CpuIOWait=$CPUIO"
        exit 1
else
        echo "OK: Used=$CPUUSED% | CpuUsed=$CPUUSED CpuUser=$CPUUSER CpuSys=$CPUUSYS CpuIOWait=$CPUIO"
        exit 0
fi
